//! Root OpenAPI document for the Madar backend.
//!
//! - [`ApiDoc`] is the single `#[derive(OpenApi)]` aggregator.
//! - Each handler annotated with `#[utoipa::path]` is registered here via
//!   the `paths(...)` list. Schemas referenced from those handlers are
//!   pulled in automatically; `components(schemas(...))` is for types
//!   that need explicit registration (rare).
//! - Bearer-JWT security scheme is added by `SecurityAddon`. Auth-gated
//!   handlers opt in with `security(("bearer_jwt" = []))` in their path
//!   attribute.
//!
//! Adding a new module's handlers means appending entries to `paths(...)`.

use utoipa::{
    Modify, OpenApi,
    openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme},
};

#[derive(OpenApi)]
#[openapi(
    info(
    title = "Madar API",
    version = env!("CARGO_PKG_VERSION"),
    description = "Madar POS — multi-tenant cafe and restaurant management. \
                   The Rust backend is the source of truth for this spec; \
                   the Flutter teller app and React management dashboard \
                   consume the generated openapi.json.",
    contact(name = "Madar", url = "https://madar-pos.cloud"),
    license(name = "Proprietary", identifier = "LicenseRef-Madar-Proprietary")
),
    servers(
        (url = "http://localhost:8080", description = "Local development"),
        (url = "https://api.madar-pos.cloud", description = "Production")
    ),
    modifiers(&SecurityAddon),
    tags(
        (name = "auth",         description = "Email/password and PIN login, JWT issuance."),
        (name = "orgs",         description = "Organization CRUD. Super-admin only."),
        (name = "branches",     description = "Branch CRUD within an organization."),
        (name = "users",        description = "User accounts, roles, and branch assignments."),
        (name = "permissions",  description = "Role permissions and per-user permission overrides."),
        (name = "menu",         description = "Categories, menu items, sizes, and addon groups."),
        (name = "recipes",      description = "Org-level recipes referencing the ingredient catalog."),
        (name = "inventory",    description = "Org-level ingredient catalog and branch-level stock."),
        (name = "orders",       description = "Order lifecycle, split payments, voids, aggregator handling."),
        (name = "shifts",       description = "Shift open/close, cash reconciliation, printable reports."),
        (name = "tills",        description = "Physical cash drawers (registers) per branch — the unit of shift concurrency and cash continuity."),
        (name = "realtime",     description = "The unified per-branch SSE bus — one connection multiplexing delivery/kitchen/tickets/orders, filtered by topic + permission."),
        (name = "kitchen",      description = "Kitchen Display System: stations, category→station routing, routing mode, the KDS feed, and per-line bump."),
        (name = "open_tickets", description = "Waiter fire-now-pay-later open tickets: fire, add rounds, settle into a paid dine-in order."),
        (name = "floor",  description = "The floor plan: section and table geometry, table occupancy derived from open tickets, and the transfer waitlist."),
        (name = "bookings", description = "Table bookings on the floor layer: settings, day list, create/edit, seat, no-show, availability, stats."),
        (name = "bookings-public", description = "Guest self-service booking: branch info, open slots, book with WhatsApp OTP, manage link."),
        (name = "floor_transfers", description = "The table-transfer waitlist: seated parties (or outside orders) queued to move to a section or a specific table."),
        (name = "stocktakes",   description = "Standalone physical-count sessions that reconcile branch stock and post variance movements."),
        (name = "purchasing",   description = "Suppliers, purchase orders, and receiving (weighted-average cost + purchase_in movements)."),
        (name = "discounts",    description = "Discount definitions and applicability rules."),
        (name = "bundles",      description = "Combo bundles and bundle pricing."),
        (name = "reports",      description = "Sales analytics and reporting."),
        (name = "integrations", description = "Read-only partner analytics pull (HTTP Basic, single-branch scope) and the org-admin surface that issues, rotates, and revokes its credentials."),
        (name = "insights",     description = "Menu profitability: the ranked margin ledger with live advisory signals, margin targets (org default + branch overrides), and the append-only decision log with measured impact."),
        (name = "uploads",      description = "Logo and image uploads."),
        (name = "payment_methods", description = "Dynamic payment methods configuration."),
        (name = "costing",      description = "Canonical recipe/addon cost rollups in piastres. NULL cost = unknown, never zero."),
        (name = "delivery",     description = "Delivery config (settings, zones, org defaults), the staff queue, status transitions, finalize, and cancel/waste."),
        (name = "delivery-public", description = "Unauthenticated, rate-limited customer endpoints: branch selector, channel menu, OSRM quote, WhatsApp OTP, order intake."),
        (name = "whatsapp",     description = "Super-admin relay to the private WhatsApp gateway: QR pairing, link status, logout, and the global send pause switch."),
        (name = "qr",           description = "Branded A6 QR card generator (PNG/SVG) and plain receipt QR. Renders a Shlink short URL into a print-perfect, Madar-styled image."),
        (name = "ai",           description = "AI analytics chat: a plain-language question over the merchant's own data, answered by picking a pre-written report (Gemini 2.5 Flash) and running it read-only, RLS-scoped."),
        (name = "staff",        description = "Employees, work shifts and rosters, GPS-verified attendance, leave/late passes/missions, and payroll. `/staff/me/*` is the employee's own self-service surface and needs no permission grant. NOTE: `work_shifts` are HR schedules — distinct from `shifts`, which are teller cash-drawer sessions.")
    ),
paths(
        // ── ai analytics chat ────────────────────────────────────────
        crate::ai::handlers::chat,
        crate::ai::stream::chat_stream,
        crate::ai::handlers::list_conversations,
        crate::ai::handlers::get_conversation,
        crate::ai::handlers::rename_conversation,
        crate::ai::handlers::delete_conversation,
        crate::analytics::handlers::schema,
        crate::analytics::handlers::query,
        // ── costing ─────────────────────────────────────────────────
        crate::costing::handlers::list_sku_costs,
        crate::orgs::onboarding::get_onboarding,
        crate::orgs::onboarding::complete_onboarding,
        crate::costing::handlers::list_addon_costs,
        // ── insights (menu profitability) ─────────────────────────────
        crate::integrations::handlers::analytics_orders,
        crate::integrations::handlers::create_credential,
        crate::integrations::handlers::list_credentials,
        crate::integrations::handlers::rotate_credential,
        crate::integrations::handlers::revoke_credential,
        crate::insights::handlers::menu_margin_ledger,
        crate::insights::handlers::margin_watch,
        crate::insights::handlers::repricing,
        crate::insights::handlers::get_margin_targets,
        crate::insights::handlers::put_margin_target,
        crate::insights::handlers::create_decision,
        crate::insights::handlers::list_decisions,
        // ── auth ────────────────────────────────────────────────────
        crate::auth::handlers::login,
        crate::auth::handlers::resolve_branch,
        crate::auth::handlers::me,
        crate::auth::handlers::permissions,
        // ── branches ────────────────────────────────────────────────
        crate::branches::handlers::list_branches,
        crate::branches::handlers::get_branch,
        crate::branches::handlers::create_branch,
        crate::branches::handlers::update_branch,
        crate::branches::handlers::delete_branch,
        crate::branches::handlers::list_timezones,
        // ── orgs ────────────────────────────────────────────────────
        crate::orgs::handlers::list_orgs,
        crate::orgs::handlers::get_org,
        crate::orgs::handlers::offline_auth_bundle,
        crate::orgs::handlers::create_org,
        crate::orgs::handlers::update_org,
        crate::orgs::handlers::upload_org_logo,
        crate::orgs::handlers::delete_org,
        crate::orgs::handlers::list_public_orgs,
        // ── users ───────────────────────────────────────────────────
        crate::users::handlers::list_users,
        crate::users::handlers::get_user,
        crate::users::handlers::create_user,
        crate::users::handlers::update_user,
        crate::users::handlers::delete_user,
        crate::users::handlers::assign_branch,
        crate::users::handlers::unassign_branch,
        crate::users::handlers::list_user_branches,
        // ── permissions ─────────────────────────────────────────────
        crate::permissions::handlers::get_user_permissions,
        crate::permissions::handlers::get_permission_matrix,
        crate::permissions::handlers::upsert_user_permission,
        crate::permissions::handlers::delete_user_permission,
        crate::permissions::handlers::get_role_permissions,
        crate::permissions::handlers::upsert_role_permission,
        // ── menu ────────────────────────────────────────────────────
        crate::menu::handlers::list_categories,
        crate::menu::handlers::create_category,
        crate::menu::handlers::update_category,
        crate::menu::handlers::delete_category,
        crate::menu::handlers::list_menu_items,
        crate::menu::handlers::list_menu_catalog,
        crate::menu::handlers::create_menu_item,
        crate::menu::handlers::get_menu_item,
        crate::menu::handlers::update_menu_item,
        crate::menu::handlers::delete_menu_item,
        crate::menu::handlers::upsert_size,
        crate::menu::handlers::delete_size,
        crate::menu::handlers::list_addon_items,
        crate::menu::handlers::list_addon_catalog,
        crate::menu::handlers::create_addon_item,
        crate::menu::handlers::update_addon_item,
        crate::menu::handlers::delete_addon_item,
        crate::menu::handlers::list_addon_slots,
        crate::menu::handlers::create_addon_slot,
        crate::menu::handlers::update_addon_slot,
        crate::menu::handlers::delete_addon_slot,
        crate::menu::handlers::list_addon_overrides,
        crate::menu::handlers::upsert_addon_override,
        crate::menu::handlers::delete_addon_override,
        crate::menu::handlers::put_allowed_addons,
        crate::menu::handlers::list_optional_fields,
        crate::menu::handlers::create_optional_field,
        crate::menu::handlers::update_optional_field,
        crate::menu::handlers::delete_optional_field,
        crate::menu::handlers::list_branch_menu_overrides,
        crate::menu::handlers::upsert_branch_menu_override,
        crate::menu::handlers::delete_branch_menu_override,
        crate::menu::handlers::list_branch_addon_overrides,
        crate::menu::handlers::upsert_branch_addon_override,
        crate::menu::handlers::delete_branch_addon_override,
        // ── menu studio (Wave 2, new unified tables) ────────────────
        crate::menu::studio::get_studio,
        crate::menu::studio::put_sizes,
        crate::menu::studio::put_size_recipe,
        crate::menu::studio::put_modifier_groups,
        crate::menu::studio::duplicate_item,
        // ── POS catalog sync (Wave 2, new unified tables) ───────────
        crate::menu::catalog_sync::catalog_sync,
        // ── menu studio: modifiers + pricing (Wave 2, new tables) ───
        crate::menu::modifiers::list_groups,
        crate::menu::modifiers::create_group,
        crate::menu::modifiers::patch_group,
        crate::menu::modifiers::delete_group,
        crate::menu::modifiers::create_option,
        crate::menu::modifiers::patch_option,
        crate::menu::modifiers::delete_option,
        crate::menu::modifiers::put_option_recipe,
        crate::menu::modifiers::put_item_options,
        crate::menu::modifiers::put_price_override,
        crate::menu::modifiers::delete_price_override,
        crate::menu::modifiers::get_item_cost,
        // ── uploads ───────────────────────────────────────────────────
        crate::uploads::handlers::upload_menu_item_image,
        // ── inventory ─────────────────────────────────────────────────
        crate::inventory::handlers::list_ingredient_categories,
        crate::inventory::handlers::create_ingredient_category,
        crate::inventory::handlers::update_ingredient_category,
        crate::inventory::handlers::delete_ingredient_category,
        crate::inventory::handlers::list_catalog,
        crate::inventory::handlers::create_catalog_item,
        crate::inventory::handlers::update_catalog_item,
        crate::inventory::handlers::delete_catalog_item,
        crate::inventory::handlers::get_inventory_settings,
        crate::inventory::handlers::update_inventory_settings,
        crate::inventory::handlers::list_branch_stock,
        crate::inventory::handlers::set_par_levels,
        crate::inventory::handlers::list_movements,
        crate::inventory::handlers::create_waste,
        crate::inventory::handlers::list_waste,
        crate::inventory::handlers::create_transfer,
        crate::inventory::handlers::list_transfers,
        crate::inventory::handlers::update_transfer,
        crate::inventory::handlers::delete_transfer,
        // ── recipes ───────────────────────────────────────────────────
        crate::recipes::steps::list_step_presets,
        crate::recipes::steps::list_recipe_steps,
        crate::recipes::steps::put_recipe_steps,
        crate::recipes::handlers::list_drink_recipes,
        crate::recipes::handlers::upsert_drink_recipe,
        crate::recipes::handlers::delete_drink_recipe,
        crate::recipes::handlers::list_addon_ingredients,
        crate::recipes::handlers::upsert_addon_ingredient,
        crate::recipes::handlers::delete_addon_ingredient,
        // ── discounts ─────────────────────────────────────────────────
        crate::discounts::handlers::list_discounts,
        crate::discounts::handlers::create_discount,
        crate::discounts::handlers::update_discount,
        crate::discounts::handlers::delete_discount,
        // ── bundles ───────────────────────────────────────────────────
        crate::bundles::handlers::list_bundles,
        crate::bundles::handlers::create_bundle,
        crate::bundles::handlers::available_bundles,
        crate::bundles::handlers::get_bundle,
        crate::bundles::handlers::update_bundle,
        crate::bundles::handlers::delete_bundle,
        crate::bundles::handlers::activate_bundle,
        crate::bundles::handlers::archive_bundle,
        crate::bundles::handlers::bundle_performance,
        // ── shifts ────────────────────────────────────────────────────
        crate::shifts::handlers::get_current_shift,
        crate::shifts::handlers::open_shift,
        crate::shifts::handlers::list_shifts,
        crate::shifts::handlers::get_shift,
        crate::shifts::handlers::get_shift_report,
        crate::shifts::handlers::add_cash_movement,
        crate::shifts::handlers::list_cash_movements,
        crate::shifts::handlers::close_shift,
        crate::shifts::handlers::force_close_shift,
        crate::shifts::handlers::delete_shift,
        crate::tills::handlers::list_tills,
        crate::tills::handlers::create_till,
        crate::tills::handlers::update_till,
        crate::tills::handlers::delete_till,
        crate::realtime::stream::stream,
        crate::kitchen::stations::list_stations,
        crate::kitchen::stations::create_station,
        crate::kitchen::stations::update_station,
        crate::kitchen::stations::delete_station,
        crate::kitchen::stations::list_routes,
        crate::kitchen::stations::put_category_route,
        crate::kitchen::stations::delete_category_route,
        crate::kitchen::stations::put_item_route,
        crate::kitchen::stations::delete_item_route,
        crate::kitchen::stations::get_routing_mode,
        crate::kitchen::stations::set_routing_mode,
        crate::kitchen::kds::feed,
        crate::kitchen::kds::bump,
        crate::kitchen::kds::unbump,
        crate::tickets::handlers::create_open_ticket,
        crate::tickets::handlers::add_round,
        crate::tickets::handlers::list_open_tickets,
        crate::tickets::handlers::get_open_ticket,
        crate::tickets::handlers::void_open_ticket,
        crate::tickets::handlers::settle_open_ticket,
        crate::tickets::handlers::move_ticket_table,
        // ── reservations + floor plan ─────────────────────────────────
        crate::reservations::floor::list_sections,
        crate::reservations::floor::create_section,
        crate::reservations::floor::update_section,
        crate::reservations::floor::delete_section,
        crate::reservations::floor::list_tables,
        crate::reservations::floor::create_table,
        crate::reservations::floor::update_table,
        crate::reservations::floor::delete_table,
        crate::reservations::floor::save_layout,
        // Bookings + public self-booking are DEPRECATED (routes unmounted by
        // default; MADAR_ENABLE_RESERVATIONS revives them) and left out of the
        // spec — the flow is being rebuilt on the new floor/held-order layer.
        // ── held orders + transfer waitlist ───────────────────────────
        crate::floor_ops::handlers::swap_tables,
        crate::floor_ops::handlers::clear_table,
        crate::floor_ops::handlers::list_floor_transfers,
        crate::floor_ops::handlers::create_floor_transfer,
        crate::floor_ops::handlers::cancel_transfer,
        crate::floor_ops::handlers::fulfill_transfer,
        // ── bookings ──────────────────────────────────────────────────
        crate::bookings::settings::get_settings,
        crate::bookings::settings::put_settings,
        crate::bookings::handlers::list_bookings,
        crate::bookings::handlers::get_booking,
        crate::bookings::handlers::create_booking,
        crate::bookings::handlers::update_booking,
        crate::bookings::handlers::cancel_booking,
        crate::bookings::handlers::no_show_booking,
        crate::bookings::handlers::seat_booking,
        crate::bookings::handlers::complete_booking,
        crate::bookings::handlers::availability,
        crate::bookings::handlers::stats,
        crate::bookings::public::booking_branches,
        crate::bookings::public::booking_info,
        crate::bookings::public::booking_slots,
        crate::bookings::public::create_public_booking,
        crate::bookings::public::get_public_booking,
        crate::bookings::public::update_public_booking,
        crate::bookings::public::cancel_public_booking,
        // ── staff: directory ──────────────────────────────────────────
        crate::staff::directory::list_departments,
        crate::staff::directory::create_department,
        crate::staff::directory::update_department,
        crate::staff::directory::delete_department,
        crate::staff::directory::list_employees,
        crate::staff::directory::get_employee,
        crate::staff::directory::put_employee,
        crate::staff::directory::delete_employee,
        crate::staff::directory::list_documents,
        crate::staff::directory::create_document,
        crate::staff::directory::delete_document,
        // ── staff: work shifts + roster ───────────────────────────────
        crate::staff::schedules::list_work_shifts,
        crate::staff::schedules::create_work_shift,
        crate::staff::schedules::update_work_shift,
        crate::staff::schedules::delete_work_shift,
        crate::staff::schedules::my_schedule,
        crate::staff::schedules::list_assignments,
        crate::staff::schedules::create_assignment,
        crate::staff::schedules::delete_assignment,
        crate::staff::schedules::put_override,
        crate::staff::schedules::delete_override,
        crate::staff::schedules::get_scheduled_day,
        // ── staff: attendance ─────────────────────────────────────────
        crate::staff::attendance::get_attendance_settings,
        crate::staff::attendance::put_attendance_settings,
        crate::staff::attendance::list_attendance,
        crate::staff::attendance::attendance_summary,
        crate::staff::attendance::team_presence,
        crate::staff::attendance::create_manual_record,
        crate::staff::attendance::correct_record,
        crate::staff::attendance::delete_record,
        crate::staff::attendance::check_in,
        crate::staff::attendance::check_out,
        crate::staff::attendance::my_today,
        crate::staff::attendance::my_attendance,
        // ── staff: leave, late passes, missions ───────────────────────
        crate::staff::requests::list_requests,
        crate::staff::requests::create_request_admin,
        crate::staff::requests::create_my_request,
        crate::staff::requests::my_requests,
        crate::staff::requests::decide_request,
        crate::staff::requests::list_leave_types,
        crate::staff::requests::create_leave_type,
        crate::staff::requests::update_leave_type,
        crate::staff::requests::delete_leave_type,
        crate::staff::requests::list_balances,
        crate::staff::requests::put_balance,
        crate::staff::requests::my_leave_balances,
        // ── staff: payroll ────────────────────────────────────────────
        crate::staff::payroll::list_deductions,
        crate::staff::payroll::create_deduction,
        crate::staff::payroll::delete_deduction,
        crate::staff::payroll::list_bonuses,
        crate::staff::payroll::create_bonus,
        crate::staff::payroll::delete_bonus,
        crate::staff::payroll::override_deduction,
        crate::staff::payroll::waive_deduction,
        crate::staff::payroll::list_advances,
        crate::staff::payroll::create_advance_admin,
        crate::staff::payroll::create_my_advance,
        crate::staff::payroll::my_advances,
        crate::staff::payroll::decide_advance,
        crate::staff::payroll::list_periods,
        crate::staff::payroll::create_period,
        crate::staff::payroll::generate_period,
        crate::staff::payroll::set_period_status,
        crate::staff::payroll::delete_period,
        crate::staff::payroll::preview_period,
        crate::staff::payroll::export_period_csv,
        crate::staff::payroll::list_payslips,
        crate::staff::payroll::my_payslips,
        // ── stocktakes ────────────────────────────────────────────────
        crate::stocktakes::handlers::create_stocktake,
        crate::stocktakes::handlers::list_stocktakes,
        crate::stocktakes::handlers::get_stocktake,
        crate::stocktakes::handlers::upsert_items,
        crate::stocktakes::handlers::finalize_stocktake,
        crate::stocktakes::handlers::cancel_stocktake,
        crate::stocktakes::handlers::variance_report,
        // ── purchasing ────────────────────────────────────────────────
        crate::purchasing::handlers::create_supplier,
        crate::purchasing::handlers::list_suppliers,
        crate::purchasing::handlers::update_supplier,
        crate::purchasing::handlers::delete_supplier,
        crate::purchasing::handlers::create_order,
        crate::purchasing::handlers::list_orders,
        crate::purchasing::handlers::list_org_orders,
        crate::purchasing::handlers::reorder_suggestions,
        crate::purchasing::handlers::create_return,
        crate::purchasing::handlers::list_po_receipts,
        crate::purchasing::handlers::get_order,
        crate::purchasing::handlers::submit_order,
        crate::purchasing::handlers::receive_order,
        crate::purchasing::handlers::cancel_order,
        // ── orders ────────────────────────────────────────────────────
        crate::orders::handlers::create_order,
        crate::orders::handlers::list_orders,
        crate::orders::handlers::get_order,
        crate::orders::handlers::void_order,
        crate::orders::handlers::preview_recipe,
        crate::orders::handlers::export_orders,
        // ── reports ───────────────────────────────────────────────────
        crate::reports::handlers::shift_summary,
        crate::reports::handlers::shift_deductions,
        crate::reports::handlers::branch_sales,
        crate::reports::handlers::branch_stock,
        crate::reports::handlers::branch_sales_timeseries,
        crate::reports::handlers::branch_sales_peak_hours,
        crate::reports::handlers::branch_teller_stats,
        crate::reports::handlers::branch_waiter_stats,
        crate::reports::handlers::branch_addon_sales,
        crate::reports::handlers::org_branch_comparison,
        crate::reports::handlers::branch_delivery_sales,
        crate::reports::handlers::branch_bundle_sales,
        crate::reports::handlers::branch_combined_item_sales,
        crate::reports::handlers::branch_inventory_valuation,
        crate::reports::handlers::org_inventory_valuation,
        crate::reports::handlers::org_low_stock,
        crate::reports::handlers::branch_low_stock,
        crate::reports::handlers::branch_consumption,
        crate::reports::handlers::branch_waste_report,
        crate::reports::handlers::branch_shrinkage,
        crate::reports::handlers::org_consumption,
        crate::reports::handlers::org_waste_report,
        crate::reports::handlers::org_shrinkage,
        // ── payment_methods ───────────────────────────────────────────
        crate::payment_methods::handlers::list_payment_methods,
        crate::payment_methods::handlers::create_payment_method,
        crate::payment_methods::handlers::update_payment_method,
        crate::payment_methods::handlers::activate_payment_method,
        crate::payment_methods::handlers::deactivate_payment_method,
        // ── delivery (admin + staff) ──────────────────────────────────
        crate::delivery::settings::get_branch_settings,
        crate::delivery::settings::put_branch_settings,
        crate::delivery::settings::set_accepting,
        crate::delivery::settings::list_zones,
        crate::delivery::settings::create_zone,
        crate::delivery::settings::update_zone,
        crate::delivery::settings::delete_zone,
        crate::delivery::settings::list_channel_overrides,
        crate::delivery::settings::upsert_channel_override,
        crate::delivery::settings::delete_channel_override,
        crate::delivery::settings::list_channel_addon_overrides,
        crate::delivery::settings::upsert_channel_addon_override,
        crate::delivery::settings::delete_channel_addon_override,
        crate::delivery::staff::list_delivery_orders,
        crate::delivery::staff::get_delivery_order,
        crate::delivery::staff::set_status,
        crate::delivery::staff::set_prep_time,
        crate::delivery::staff::cancel_delivery_order,
        crate::delivery::staff::finalize_delivery_order,
        // ── delivery (public) ─────────────────────────────────────────
        crate::delivery::public::public_branches,
        crate::delivery::public::public_menu,
        crate::delivery::public::delivery_quote,
        crate::delivery::public::otp_request,
        crate::delivery::public::otp_verify,
        crate::delivery::public::create_delivery_order,
        crate::delivery::public::track_delivery_order,
        crate::delivery::public::guest_order_history,
        crate::delivery::public::guest_past_locations,
        // ── whatsapp gateway relay (super-admin) ──────────────────────
        crate::delivery::gateway::status,
        crate::delivery::gateway::pair,
        crate::delivery::gateway::logout,
        crate::delivery::gateway::pause,
        // ── qr (dynamic short-URL + branded card) ────────────────────
        crate::qr_card::handlers::org_qr,
        crate::qr_card::handlers::branch_booking_qr,
        crate::qr_card::handlers::org_booking_qr,
        crate::qr_card::handlers::branch_qr,
        crate::qr_card::handlers::create_table,
        crate::qr_card::handlers::list_tables,
        crate::qr_card::handlers::delete_table,
        crate::qr_card::handlers::table_qr,
        crate::qr_card::handlers::delivery_order_qr,
        crate::qr_card::handlers::create_marketing_link,
        crate::qr_card::handlers::list_marketing_links,
    ),
    components(schemas(
        // Most schemas are pulled in transitively via path responses, but
        // listing the shared error body explicitly makes it discoverable.
        crate::errors::ErrorBody,
        crate::ai::handlers::AiChatRequest,
        crate::ai::handlers::AiChatResponse,
        crate::ai::handlers::AiChatKind,
        crate::ai::handlers::HistoryTurn,
        crate::ai::handlers::ResultBlock,
        crate::ai::stream::ChatFrame,
        crate::ai::handlers::ConversationList,
        crate::ai::handlers::RenameConversationRequest,
        crate::ai::store::ConversationSummary,
        crate::ai::store::ConversationDetail,
        crate::ai::store::StoredTurn,
        crate::analytics::handlers::MetricsQueryRequest,
        crate::analytics::handlers::MetricsQueryResponse,
        crate::analytics::handlers::WidgetRequest,
        crate::analytics::handlers::WidgetOutcome,
        crate::analytics::handlers::MetricResult,
        crate::analytics::handlers::PeriodInfo,
        crate::analytics::registry::RegistryInfo,
        crate::analytics::registry::DatasetInfo,
        crate::analytics::registry::FieldInfo,
        crate::analytics::registry::FilterInfo,
        crate::analytics::registry::PresetInfo,
        crate::analytics::registry::BoardInfo,
        crate::analytics::scope::ScopeInfo,
        crate::analytics::spec::QuerySpec,
        crate::analytics::spec::Period,
        crate::analytics::spec::PeriodPreset,
        crate::analytics::spec::Sort,
        crate::analytics::spec::TopPer,
        crate::analytics::spec::Transform,
        crate::analytics::types::Column,
        crate::analytics::types::ColumnKind,
        crate::analytics::types::Compare,
        crate::analytics::types::Dir,
        crate::analytics::types::Grain,
        crate::analytics::types::Viz,
        crate::auth::handlers::ResolveBranchRequest,
        crate::auth::handlers::ResolveBranchResponse,
        // GET /orders?include_items=true response shape (the annotation's
        // `body` documents the default PaginatedOrders variant).
        crate::orders::handlers::PaginatedOrdersFull,
        // Delivery context nested on the single-order detail (GET /orders/{id}).
        crate::orders::handlers::OrderDeliveryInfo,
        crate::shifts::handlers::PaginatedShifts,
        crate::tills::handlers::Till,
        crate::tills::handlers::CreateTillRequest,
        crate::tills::handlers::UpdateTillRequest,
        // ── reservations + floor plan ─────────────────────────────────
        crate::reservations::floor::FloorSection,
        crate::reservations::floor::FloorTable,
        crate::reservations::floor::CreateSectionRequest,
        crate::reservations::floor::UpdateSectionRequest,
        crate::reservations::floor::CreateFloorTableRequest,
        crate::reservations::floor::UpdateFloorTableRequest,
        crate::reservations::floor::TablePosition,
        crate::reservations::floor::SaveLayoutRequest,
        // ── staff / attendance / payroll ──────────────────────────────
        crate::staff::rules::AttendanceStatus,
        crate::staff::rules::LateDeductionKind,
        crate::staff::rules::LateTier,
        crate::staff::directory::Department,
        crate::staff::directory::Employee,
        crate::staff::directory::StaffDocument,
        crate::staff::schedules::WorkShift,
        crate::staff::schedules::ScheduleAssignment,
        crate::staff::schedules::ScheduleOverride,
        crate::staff::schedules::ResolvedShift,
        crate::staff::attendance::AttendanceRecord,
        crate::staff::attendance::AttendanceSettings,
        crate::staff::attendance::AttendanceSummary,
        crate::staff::attendance::TeamPresence,
        crate::staff::attendance::PresenceRow,
        crate::staff::schedules::ScheduledDay,
        crate::staff::attendance::MyAttendanceToday,
        crate::staff::requests::StaffRequest,
        crate::staff::requests::CreateStaffRequest,
        crate::staff::requests::RequestDecision,
        crate::staff::payroll::AdvanceDecision,
        crate::staff::requests::LeaveType,
        crate::staff::requests::LeaveBalance,
        crate::staff::payroll::PayrollAdjustment,
        crate::staff::payroll::SalaryAdvance,
        crate::staff::payroll::PayrollPeriod,
        crate::staff::payroll::Payslip,
        crate::staff::payroll::ComputedPayslip,
        crate::tickets::handlers::MoveTicketTableRequest,
        // ── held orders + transfer waitlist ───────────────────────────
        crate::floor_ops::TransferView,
        crate::floor_ops::TransfersSyncResponse,
        crate::floor_ops::handlers::SwapTablesRequest,
        crate::floor_ops::handlers::ClearTableRequest,
        crate::floor_ops::handlers::CreateFloorTransferRequest,
        crate::floor_ops::handlers::FulfillTransferRequest,
        crate::kitchen::stations::KitchenStation,
        crate::kitchen::stations::StationRoutes,
        crate::kitchen::stations::RoutingModeResponse,
        crate::kitchen::KitchenTicketView,
        crate::kitchen::KitchenTicketItemView,
        crate::kitchen::KitchenLine,
        crate::tickets::OpenTicketView,
        crate::tickets::OpenTicketItemView,
        crate::menu::handlers::PaginatedMenuItems,
        crate::menu::handlers::MenuItemWithCosts,
        crate::menu::handlers::PaginatedAddonItems,
        crate::menu::handlers::BranchMenuOverride,
        crate::menu::handlers::BranchMenuOverrideInput,
        crate::menu::handlers::BranchSizeOverride,
        crate::menu::handlers::BranchSizeOverrideInput,
        crate::menu::handlers::BranchAddonOverride,
        crate::menu::handlers::BranchAddonOverrideInput,
        // ── delivery ──────────────────────────────────────────────────
        crate::delivery::settings::BranchDeliverySettings,
        crate::delivery::settings::DeliveryZone,
        crate::delivery::settings::ChannelMenuOverride,
        crate::delivery::settings::ChannelAddonOverride,
        crate::delivery::staff::DeliveryOrder,
        crate::delivery::staff::FinalizeResponse,
        crate::delivery::public::PublicBranch,
        crate::delivery::public::DeliveryMenu,
        crate::delivery::public::DeliveryMenuDiscount,
        crate::delivery::public::DeliveryMenuItem,
        crate::delivery::public::DeliveryMenuSize,
        crate::delivery::public::DeliveryMenuCategory,
        crate::delivery::public::DeliveryAddonOption,
        crate::delivery::public::DeliveryOptionalField,
        crate::delivery::public::QuoteResponse,
        crate::delivery::public::OtpRequestResponse,
        crate::delivery::public::OtpVerifyResponse,
        crate::delivery::public::DeliveryTracking,
        crate::delivery::snapshot::CartLineInput,
        crate::delivery::gateway::WhatsappStatus,
        crate::delivery::gateway::PauseInput,
        // ── qr ────────────────────────────────────────────────────────
        crate::qr_card::handlers::QrResponse,
        crate::qr_card::handlers::MarketingLink,
        crate::qr_card::handlers::CreateMarketingLinkRequest,
        crate::qr_card::db::BranchTable,
        crate::qr_card::db::CreateTableRequest,
    ))
)]
pub struct ApiDoc;

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi
            .components
            .as_mut()
            .expect("OpenAPI components should exist after derive");

        components.add_security_scheme(
            "basic_integration",
            SecurityScheme::Http(
                HttpBuilder::new()
                    .scheme(HttpAuthScheme::Basic)
                    .description(Some(
                        "Partner analytics credential issued from the dashboard \
                         (`POST /integrations/credentials`). Send as \
                         `Authorization: Basic base64(username:secret)`. Read-only \
                         and scoped to a single branch.",
                    ))
                    .build(),
            ),
        );

        components.add_security_scheme(
            "bearer_jwt",
            SecurityScheme::Http(
                HttpBuilder::new()
                    .scheme(HttpAuthScheme::Bearer)
                    .bearer_format("JWT")
                    .description(Some(
                        "JWT obtained from `POST /auth/login` (email/password) or \
                         `POST /auth/pin-login` (teller PIN). Send as \
                         `Authorization: Bearer <token>`.",
                    ))
                    .build(),
            ),
        );
    }
}
